### ISSUE TITLE
Unintuitive input format

### ISSUE THREAD

**Issue by Steeeephen** [Steeeephen/LAVA#18]
Currently the input format for local videos makes no fucking sense

* Add video to `input/` folder
* Specify the path *within* the `input/` folder (not the full filename)
* LAVA takes the path and uses that for the output filename

This is a symptom of postgrad me being an idiot code-wise, will fix it to just use the full path

**Comment by Allan-Cao** [comment]
I can work on this as this has been the biggest blocker for me to test stuff haha. (been just doing it directly by declaring a class instance)

**Comment by Steeeephen** [comment]
Thanks @Allan-Cao

**Comment by Allan-Cao** [comment]
Addressed in #24
