### ISSUE TITLE
Indentation

### ISSUE THREAD

**Issue by Allan-Cao** [Steeeephen/LAVA#21]
Hi! I'm wondering if we could change the global styling to match PEP-8 guidelines with four spaces of indentation.

**Comment by Steeeephen** [comment]
It's definitely the plan and is fairly low-hanging fruit, a big refactor is needed and pep8 will be a part of it for sure

**Comment by Allan-Cao** [comment]
I can apply this styling as well as other stylings with black fairly easily. Perhaps we can adopt that code formatting? https://github.com/psf/black

**Comment by Allan-Cao** [comment]
See PR #22 for black formatting

**Comment by Steeeephen** [comment]
ah damn you beat me to it, merged #23 already. The other OSS I'm maintaining just go with flake8 and base pep8 rather than black so may as well stick to it
